### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by qxygene** [videsk/iFrameX#4]
append: '#myid',

append is not working

**Comment by matiaslopezd** [comment]
Hi @qxygene can you send your example code?

iFrameX use `querySelector(string)`. Maybe your app remove the element with id `myid` before iFrameX can append iframe.

**Comment by matiaslopezd** [comment]
I tried to reproduce your problem and maybe you tried to append elements on `#myid` and the order of elements in the object is not correct. In others words try to check if the order of elements is correct because the library goes creating elements with a mapping on `Object.keys(elements).map(key => ...)`. For example, when iFrameX try to append a img on a `div#myid`, needs `div#myid` exist before append img.

**Incorrect way**
```js
[
    {
        type: 'img',
        append: '#myid',
        attr: {
            src: 'https://mywebsite.com/img/1.png'
        }
    }
    {
        type: 'div',
        append: 'body',
        attr: {
            id: 'myid'
        }
    },
]
```

**Correct way**

```js
[
    {
        type: 'div',
        append: 'body',
        attr: {
            id: 'myid'
        }
    },
    {
        type: 'img',
        append: '#myid',
        attr: {
            src: 'https://mywebsite.com/img/1.png'
        }
    }
]
```

**Comment by matiaslopezd** [comment]
New version 3.0.0, please test and comment if continue with the issue.
